import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang={"en"} suppressHydrationWarning>
      <body className={"relative min-h-[100dvh]"}>{children}</body>
    </html>
  );
}
