import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from "@/context/AuthProvider";
import ServerIntlProvider from "@/context/i18nProvider";
import getIntl from "@/server/lib/intl";
import { FetchProvider } from "@/context/FetchProvider";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { Header } from "@/components/header/Header";
import { Background } from "@/components/background";
import { ProviderTheme } from "@/context/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale?: string }>;
}>) {
  const { locale } = await params;
  const safeLocale = ["en-US", "uk-UA"].includes(locale ?? "")
    ? locale!
    : "en-US";
  const intl = await getIntl(safeLocale);

  return (
    <ServerIntlProvider messages={intl.messages} locale={intl.locale}>
      <FetchProvider>
        <AuthProvider>
          <ProviderTheme>
            <Header />
            {children}
            <Background />
            <Toaster />
          </ProviderTheme>
        </AuthProvider>
      </FetchProvider>
    </ServerIntlProvider>
  );
}

export function generateStaticParams(): Array<{ locale: string }> {
  const locales = ["en-US", "uk-UA"];

  return locales.map((locale) => ({ locale }));
}
