import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from "@/context/AuthProvider";
import ServerIntlProvider from "@/context/i18nProvider";
import getIntl from "@/lib/intl";
import { FetchProvider } from "@/context/FetchProvider";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { Header } from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string | undefined }>;
}>) {
  const { locale } = await params;
  const intl = await getIntl(locale);
  return (
    <ServerIntlProvider messages={intl.messages} locale={intl.locale}>
      <FetchProvider>
        <AuthProvider>
          <Header />
          {children}
          <Toaster />
        </AuthProvider>
      </FetchProvider>
    </ServerIntlProvider>
  );
}

export function generateStaticParams(): Array<{ locale: string }> {
  const locales = ["en-US", "uk-UA"];

  return locales.map((locale) => ({ locale }));
}
