import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from "@/context/AuthProvider";
import ServerIntlProvider from "@/context/i18nProvider";
import getIntl from "@/lib/intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout<T>({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<T>;
}>) {
  const { locale } = await params;
  const intl = await getIntl(locale);
  return (
    <ServerIntlProvider messages={intl.messages} locale={intl.locale}>
      <AuthProvider>{children}</AuthProvider>
    </ServerIntlProvider>
  );
}
